import{S as L,a as b,i as m}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const u=document.querySelector(".gallery");let v=new L(".gallery a",{captionsData:"alt",captionDelay:250});function f(e){return`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
      <img src="${e.webformatURL}" alt="${e.tags}">
      <div class="card-body">
        <p class="card-text">Likes: ${e.likes}</p>
        <p class="card-text">Views: ${e.views}</p>
        <p class="card-text">Comments: ${e.comments}</p>
        <p class="card-text">Downloads: ${e.downloads}</p>
      </div>
      </a>
    </li>`}function p(e){const r=e.map(o=>f(o)).join("");u.insertAdjacentHTML("beforeend",r),v.refresh()}let g=0;async function y(e,r=1){const o=`https://pixabay.com/api/?key=33929638-3d09c2b606ca8b58d00360aed&q=${e}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`,a=await b.get(o);return g=a.data.totalHits,a.data.hits}const w=document.querySelector("#searchInput"),S=document.querySelector('button[type="submit"]'),P=document.querySelector(".js-form"),d=document.querySelector(".loader"),n=document.querySelector(".load");let i="",c=1;const R=15;S.addEventListener("click",q);n.addEventListener("click",x);async function q(e){if(e.preventDefault(),i=w.value.trim(),!!i){d.classList.add("is-shown"),u.innerHTML="",P.reset();try{const r=await y(i);r.length?(d.classList.remove("is-shown"),c=1,f(r),p(r),n.classList.remove("hidden")):(m.error({title:"Sorry",message:"There are no images matching your search query. Please try again!",position:"topRight"}),d.classList.remove("is-shown"))}catch(r){console.error("Error:",r)}h()}}async function x(){c+=1;const e=await y(i,c);f(e),p(e),h(),window.scrollBy({top:u.firstElementChild.getBoundingClientRect().height*2,behavior:"smooth"})}function h(){Math.ceil(g/R)<=c?(n.classList.add("hidden"),m.error({title:"Sorry",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):n.classList.remove("hidden")}
//# sourceMappingURL=commonHelpers.js.map
